In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer
from sklearn.preprocessing import StandardScaler
import warnings

warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("../data/raw/heart.csv")

In [3]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [4]:
df.sample(5)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
255,53,F,NAP,120,274,0,Normal,130,N,0.0,Up,0
760,53,M,ASY,123,282,0,Normal,95,Y,2.0,Flat,1
265,54,M,ATA,160,305,0,Normal,175,N,0.0,Up,0
250,44,M,ASY,135,491,0,Normal,135,N,0.0,Flat,1
642,51,F,NAP,120,295,0,LVH,157,N,0.6,Up,0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    str
 2   ChestPainType   918 non-null    str
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    str
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    str
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    str
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), str(5)
memory usage: 97.6 KB

In [6]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [7]:
df.describe(include='all')

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
count,918.000000,918,918,918.000000,918.000000,918.000000,918,918.000000,918,918.000000,918,918.000000
unique,NaN,2,4,NaN,NaN,NaN,3,NaN,2,NaN,3,NaN
top,NaN,M,ASY,NaN,NaN,NaN,Normal,NaN,N,NaN,Flat,NaN
freq,NaN,725,496,NaN,NaN,NaN,552,NaN,547,NaN,460,NaN
mean,53.510893,NaN,NaN,132.396514,198.799564,0.233115,NaN,136.809368,NaN,0.887364,NaN,0.553377
std,9.432617,NaN,NaN,18.514154,109.384145,0.423046,NaN,25.460334,NaN,1.066570,NaN,0.497414
min,28.000000,NaN,NaN,0.000000,0.000000,0.000000,NaN,60.000000,NaN,-2.600000,NaN,0.000000
25%,47.000000,NaN,NaN,120.000000,173.250000,0.000000,NaN,120.000000,NaN,0.000000,NaN,0.000000
50%,54.000000,NaN,NaN,130.000000,223.000000,0.000000,NaN,138.000000,NaN,0.600000,NaN,1.000000
75%,60.000000,NaN,NaN,140.000000,267.000000,0.000000,NaN,156.000000,NaN,1.500000,NaN,1.000000
max,77.000000,NaN,NaN,200.000000,603.000000,1.000000,NaN,202.000000,NaN,6.200000,NaN,1.000000

In [8]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.nunique()

Age                50
Sex                 2
ChestPainType       4
RestingBP          67
Cholesterol       222
FastingBS           2
RestingECG          3
MaxHR             119
ExerciseAngina      2
Oldpeak            53
ST_Slope            3
HeartDisease        2
dtype: int64

In [11]:
df['Cholesterol'].value_counts()

Cholesterol
0      172
254     11
223     10
220     10
211      9
      ...
353      1
278      1
157      1
176      1
131      1
Name: count, Length: 222, dtype: int64

In [12]:
df['Cholesterol']=df['Cholesterol'].replace(0,np.nan)

In [13]:
df['RestingBP'].value_counts()

RestingBP
120    132
130    118
140    107
110     58
150     55
      ...
174      1
117      1
192      1
129      1
164      1
Name: count, Length: 67, dtype: int64

In [14]:
df[df['RestingBP']==0]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
449,55,M,NAP,0,NaN,0,Normal,155,N,1.5,Flat,1

In [15]:
df['RestingBP']=df['RestingBP'].replace(0,np.nan)

In [16]:
X = df.drop('HeartDisease', axis=1)
y = df['HeartDisease']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [17]:
cols_numeriques = ['Age', 'RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak']

X_train_num = X_train[cols_numeriques].copy()

X_train_complet = X_train_num.dropna(subset=['RestingBP'])

k_a_tester = [3, 5, 7, 9, 10, 11]

resultats_bp = {k: [] for k in k_a_tester}

for essai in range(1, 6):
    
    echantillon = X_train_complet.sample(
        frac=0.2,
        random_state=42 + essai
    )
    
    df_ref = X_train_complet.drop(echantillon.index)
    
    echantillon_masque = echantillon.copy()
    echantillon_masque['RestingBP'] = np.nan

    df_a_imputer = pd.concat([
        df_ref,
        echantillon_masque
    ])
    
    vraies_valeurs = echantillon['RestingBP']
    
    for k in k_a_tester:
        
        imputer = KNNImputer(
            n_neighbors=k,
            weights='uniform',
            metric='nan_euclidean'
        )
        
        df_impute = pd.DataFrame(
            imputer.fit_transform(df_a_imputer),
            columns=cols_numeriques,
            index=df_a_imputer.index
        )
        
        pred = df_impute.loc[echantillon.index, 'RestingBP']
        
        mae = np.mean(
            np.abs(pred - vraies_valeurs)
        )
        
        resultats_bp[k].append(mae)

In [18]:
meilleur_k_bp = None
meilleure_mae_bp = float('inf')

for k in k_a_tester:
    
    mae_moyenne = np.mean(resultats_bp[k])
    
    print(f"K={k:2d} -> MAE RestingBP = {mae_moyenne:.4f}")
    
    if mae_moyenne < meilleure_mae_bp:
        meilleure_mae_bp = mae_moyenne
        meilleur_k_bp = k

print(
    f"\n MEILLEUR K POUR RestingBP = {meilleur_k_bp} "
    f"(MAE = {meilleure_mae_bp:.4f})"
)

K= 3 -> MAE RestingBP = 16.2898
K= 5 -> MAE RestingBP = 15.2484
K= 7 -> MAE RestingBP = 14.6237
K= 9 -> MAE RestingBP = 14.1684
K=10 -> MAE RestingBP = 14.0459
K=11 -> MAE RestingBP = 13.9203

 MEILLEUR K POUR RestingBP = 11 (MAE = 13.9203)

In [19]:
X_train_complet = X_train_num.dropna(subset=['Cholesterol'])

k_a_tester = [3, 5, 7, 9, 10, 11]

resultats_chol = {k: [] for k in k_a_tester}

for essai in range(1, 6):
    
    echantillon = X_train_complet.sample(
        frac=0.2,
        random_state=42 + essai
    )
    
    df_ref = X_train_complet.drop(echantillon.index)
    
    echantillon_masque = echantillon.copy()
    echantillon_masque['Cholesterol'] = np.nan
    
    df_a_imputer = pd.concat([
        df_ref,
        echantillon_masque
    ])
    
    vraies_valeurs = echantillon['Cholesterol']
    
    for k in k_a_tester:
        
        imputer = KNNImputer(
            n_neighbors=k,
            weights='uniform',
            metric='nan_euclidean'
        )
        
        df_impute = pd.DataFrame(
            imputer.fit_transform(df_a_imputer),
            columns=cols_numeriques,
            index=df_a_imputer.index
        )
        
        pred = df_impute.loc[
            echantillon.index,
            'Cholesterol'
        ]
        
        mae = np.mean(
            np.abs(pred - vraies_valeurs)
        )
        
        resultats_chol[k].append(mae)

In [20]:
meilleur_k_chol = None
meilleure_mae_chol = float('inf')

for k in k_a_tester:
    
    mae_moyenne = np.mean(resultats_chol[k])
    
    print(
        f"K={k:2d} -> MAE Cholesterol = {mae_moyenne:.4f}"
    )
    
    if mae_moyenne < meilleure_mae_chol:
        meilleure_mae_chol = mae_moyenne
        meilleur_k_chol = k

print(
    f"\n MEILLEUR K POUR Cholesterol = {meilleur_k_chol} "
    f"(MAE = {meilleure_mae_chol:.4f})"
)

K= 3 -> MAE Cholesterol = 49.2193
K= 5 -> MAE Cholesterol = 47.5593
K= 7 -> MAE Cholesterol = 45.5481
K= 9 -> MAE Cholesterol = 44.5844
K=10 -> MAE Cholesterol = 44.0726
K=11 -> MAE Cholesterol = 43.5752

 MEILLEUR K POUR Cholesterol = 11 (MAE = 43.5752)

In [21]:
from sklearn.impute import KNNImputer

cols_numeriques = [
    'Age',
    'RestingBP',
    'Cholesterol',
    'MaxHR',
    'Oldpeak'
]

imputer = KNNImputer(
    n_neighbors=11,
    weights='uniform',
    metric='nan_euclidean'
)

X_train_num_imputed = pd.DataFrame(
    imputer.fit_transform(X_train[cols_numeriques]),
    columns=cols_numeriques,
    index=X_train.index
)

In [22]:
X_test_num_imputed = pd.DataFrame(
    imputer.transform(X_test[cols_numeriques]),
    columns=cols_numeriques,
    index=X_test.index
)

In [23]:
cols_categoriques =[ 'Sex','FastingBS', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']

In [24]:
X_train_cat = pd.get_dummies(
    X_train[cols_categoriques],
    drop_first=True
)

In [25]:
X_test_cat = pd.get_dummies(
    X_test[cols_categoriques],
    drop_first=True
)

In [26]:
bool_cols_train = X_train_cat.select_dtypes(include='bool').columns
X_train_cat[bool_cols_train] = X_train_cat[bool_cols_train].astype(int)

bool_cols_test = X_test_cat.select_dtypes(include='bool').columns
X_test_cat[bool_cols_test] = X_test_cat[bool_cols_test].astype(int)

In [27]:
print("Train :", X_train_cat.columns.tolist())
print("Test  :", X_test_cat.columns.tolist())

Train : ['FastingBS', 'Sex_M', 'ChestPainType_ATA', 'ChestPainType_NAP', 'ChestPainType_TA', 'RestingECG_Normal', 'RestingECG_ST', 'ExerciseAngina_Y', 'ST_Slope_Flat', 'ST_Slope_Up']
Test  : ['FastingBS', 'Sex_M', 'ChestPainType_ATA', 'ChestPainType_NAP', 'ChestPainType_TA', 'RestingECG_Normal', 'RestingECG_ST', 'ExerciseAngina_Y', 'ST_Slope_Flat', 'ST_Slope_Up']

In [28]:
print(X_train_cat.shape)
print(X_test_cat.shape)

(734, 10)
(184, 10)

In [29]:
X_train_final = pd.concat(
    [X_train_num_imputed, X_train_cat],
    axis=1
)

X_test_final = pd.concat(
    [X_test_num_imputed, X_test_cat],
    axis=1
)

In [30]:
print("X_train_final :", X_train_final.shape)
print("X_test_final :", X_test_final.shape)

X_train_final : (734, 15)
X_test_final : (184, 15)

In [31]:
scaler = StandardScaler()
cols_numeriques = ['Age', 'RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak']

X_train_scaled = X_train_final.copy()
X_test_scaled = X_test_final.copy()

X_train_scaled[cols_numeriques] = scaler.fit_transform(
    X_train_final[cols_numeriques]
)

X_test_scaled[cols_numeriques] = scaler.transform(
    X_test_final[cols_numeriques]
)

In [32]:
X_train_final.to_csv("../data/processed/X_train_final.csv", index=False)
X_test_final.to_csv("../data/processed/X_test_final.csv", index=False)

y_train.to_csv("../data/processed/y_train.csv", index=False)
y_test.to_csv("../data/processed/y_test.csv", index=False)

In [33]:
pd.DataFrame(X_train_scaled, columns=X_train_final.columns).to_csv(
    "../data/processed/X_train_scaled.csv", index=False
)

pd.DataFrame(X_test_scaled, columns=X_test_final.columns).to_csv(
    "../data/processed/X_test_scaled.csv", index=False
)

In [34]:
print("X_train_final :", X_train_final.shape)
print("X_test_final  :", X_test_final.shape)

print("X_train_scaled :", X_train_scaled.shape)
print("X_test_scaled  :", X_test_scaled.shape)

print("y_train :", y_train.shape)
print("y_test  :", y_test.shape)

X_train_final : (734, 15)
X_test_final  : (184, 15)
X_train_scaled : (734, 15)
X_test_scaled  : (184, 15)
y_train : (734,)
y_test  : (184,)

In [35]:
print("NaN train :", X_train_final.isnull().sum().sum())
print("NaN test  :", X_test_final.isnull().sum().sum())

NaN train : 0
NaN test  : 0

In [36]:
import joblib

joblib.dump(scaler, "../models/scaler.pkl")

['../models/scaler.pkl']