In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/heart.csv")

In [4]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [5]:
df.sample(5)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
207,35,M,ATA,110,257,0,Normal,140,N,0.0,Flat,1
645,57,M,NAP,128,229,0,LVH,150,N,0.4,Flat,1
346,59,M,ASY,120,0,0,Normal,115,N,0.0,Flat,1
511,63,M,ASY,160,267,1,ST,88,Y,2.0,Flat,1
285,51,F,NAP,110,190,0,Normal,120,N,0.0,Up,0

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    str
 2   ChestPainType   918 non-null    str
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    str
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    str
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    str
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), str(5)
memory usage: 97.6 KB

In [7]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [8]:
df.describe(include='all')

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
count,918.000000,918,918,918.000000,918.000000,918.000000,918,918.000000,918,918.000000,918,918.000000
unique,NaN,2,4,NaN,NaN,NaN,3,NaN,2,NaN,3,NaN
top,NaN,M,ASY,NaN,NaN,NaN,Normal,NaN,N,NaN,Flat,NaN
freq,NaN,725,496,NaN,NaN,NaN,552,NaN,547,NaN,460,NaN
mean,53.510893,NaN,NaN,132.396514,198.799564,0.233115,NaN,136.809368,NaN,0.887364,NaN,0.553377
std,9.432617,NaN,NaN,18.514154,109.384145,0.423046,NaN,25.460334,NaN,1.066570,NaN,0.497414
min,28.000000,NaN,NaN,0.000000,0.000000,0.000000,NaN,60.000000,NaN,-2.600000,NaN,0.000000
25%,47.000000,NaN,NaN,120.000000,173.250000,0.000000,NaN,120.000000,NaN,0.000000,NaN,0.000000
50%,54.000000,NaN,NaN,130.000000,223.000000,0.000000,NaN,138.000000,NaN,0.600000,NaN,1.000000
75%,60.000000,NaN,NaN,140.000000,267.000000,0.000000,NaN,156.000000,NaN,1.500000,NaN,1.000000
max,77.000000,NaN,NaN,200.000000,603.000000,1.000000,NaN,202.000000,NaN,6.200000,NaN,1.000000

In [9]:
df.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.nunique()

Age                50
Sex                 2
ChestPainType       4
RestingBP          67
Cholesterol       222
FastingBS           2
RestingECG          3
MaxHR             119
ExerciseAngina      2
Oldpeak            53
ST_Slope            3
HeartDisease        2
dtype: int64

In [12]:
df['Cholesterol'].value_counts()

Cholesterol
0      172
254     11
223     10
220     10
211      9
      ...
353      1
278      1
157      1
176      1
131      1
Name: count, Length: 222, dtype: int64

In [13]:
df['Cholesterol']=df['Cholesterol'].replace(0,np.nan)

In [14]:
df['RestingBP'].value_counts()

RestingBP
120    132
130    118
140    107
110     58
150     55
      ...
174      1
117      1
192      1
129      1
164      1
Name: count, Length: 67, dtype: int64

In [15]:
df[df['RestingBP']==0]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
449,55,M,NAP,0,NaN,0,Normal,155,N,1.5,Flat,1

In [16]:
df['RestingBP']=df['RestingBP'].replace(0,np.nan)

In [17]:
from sklearn.impute import KNNImputer


cols_numeriques = ['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak']

cols_a_imputer = ['RestingBP', 'Cholesterol']

cible = 'HeartDisease'

df_numerique = df[cols_numeriques].copy()

df_complet = df_numerique.dropna(subset=cols_a_imputer).copy()

df_manquant = df_numerique[df_numerique[cols_a_imputer].isnull().any(axis=1)].copy()

print(f"Lignes complètes : {len(df_complet)}")
print(f"Lignes avec des NaN : {len(df_manquant)}")
print("")

k_a_tester = [3, 5, 7, 9, 10, 11]
resultats_par_k = {k: [] for k in k_a_tester}

for test in range(1, 4):
    print(f" Test {test} (random seed = {42+test})")
    
    taille_echantillon = int(0.2 * len(df_complet))
    echantillon = df_complet.sample(n=taille_echantillon, random_state=42+test)
    
    df_reference = df_complet.drop(echantillon.index)
    
    echantillon_masque = echantillon.copy()
    echantillon_masque[cols_a_imputer] = np.nan
    
    df_a_imputer = pd.concat([df_reference, echantillon_masque], axis=0)
    
    vraies_valeurs = echantillon[cols_a_imputer].copy()
    
    print(f" Échantillon test : {len(echantillon)} lignes")
    
    for k in k_a_tester:
        imputer = KNNImputer(n_neighbors=k, weights='uniform', metric='nan_euclidean')
        df_impute_temp = pd.DataFrame(
            imputer.fit_transform(df_a_imputer),
            columns=cols_numeriques
        )
        
        debut_echantillon = len(df_reference)
        echantillon_impute = df_impute_temp.iloc[debut_echantillon:].copy()
        
        bp_impute = echantillon_impute['RestingBP'].values
        chol_impute = echantillon_impute['Cholesterol'].values
        
        bp_reel = vraies_valeurs['RestingBP'].values
        chol_reel = vraies_valeurs['Cholesterol'].values
        
        mae_bp = np.mean(np.abs(bp_impute - bp_reel))
        mae_chol = np.mean(np.abs(chol_impute - chol_reel))
        mae_moyenne = (mae_bp + mae_chol) / 2
        
        resultats_par_k[k].append(mae_moyenne)
        print(f"    K={k} -> MAE moyenne = {mae_moyenne:.2f} (BP: {mae_bp:.2f} | Chol: {mae_chol:.2f})")

print("\n RÉSULTATS FINAUX (moyenne sur les 3 tests) ")
meilleur_k = None
meilleure_mae = 9999

for k in k_a_tester:
    mae_moyenne = np.mean(resultats_par_k[k])
    print(f"K={k} -> MAE moyenne = {mae_moyenne:.2f}")
    if mae_moyenne < meilleure_mae:
        meilleure_mae = mae_moyenne
        meilleur_k = k

print(f" MEILLEUR K : K = {meilleur_k}  (MAE moyenne = {meilleure_mae:.2f})")

df_total = pd.concat([df_complet, df_manquant], axis=0)

imputer_final = KNNImputer(n_neighbors=meilleur_k, weights='uniform', metric='nan_euclidean')
df_impute_final = pd.DataFrame(
    imputer_final.fit_transform(df_total),
    columns=cols_numeriques
)

nb_nan = df_impute_final[cols_a_imputer].isnull().sum().sum()
print(f"NaN restants après imputation : {nb_nan}")

df_original = df.copy()
df_original[cols_numeriques] = df_impute_final

df = df_original

Lignes complètes : 746
Lignes avec des NaN : 172

 Test 1 (random seed = 43)
 Échantillon test : 149 lignes
    K=3 -> MAE moyenne = 35.96 (BP: 16.61 | Chol: 55.31)
    K=5 -> MAE moyenne = 34.28 (BP: 15.36 | Chol: 53.19)
    K=7 -> MAE moyenne = 33.05 (BP: 15.05 | Chol: 51.06)
    K=9 -> MAE moyenne = 32.39 (BP: 14.80 | Chol: 49.98)
    K=10 -> MAE moyenne = 32.16 (BP: 14.67 | Chol: 49.66)
    K=11 -> MAE moyenne = 31.88 (BP: 14.68 | Chol: 49.09)
 Test 2 (random seed = 44)
 Échantillon test : 149 lignes
    K=3 -> MAE moyenne = 33.98 (BP: 14.52 | Chol: 53.45)
    K=5 -> MAE moyenne = 30.91 (BP: 13.28 | Chol: 48.55)
    K=7 -> MAE moyenne = 31.02 (BP: 12.47 | Chol: 49.57)
    K=9 -> MAE moyenne = 30.33 (BP: 12.62 | Chol: 48.03)
    K=10 -> MAE moyenne = 30.04 (BP: 12.60 | Chol: 47.48)
    K=11 -> MAE moyenne = 29.30 (BP: 12.61 | Chol: 46.00)
 Test 3 (random seed = 45)
 Échantillon test : 149 lignes
    K=3 -> MAE moyenne = 33.59 (BP: 14.50 | Chol: 52.68)
    K=5 -> MAE moyenne = 32.48 (BP: 13.30 | Chol: 51.66)
    K=7 -> MAE moyenne = 30.38 (BP: 13.04 | Chol: 47.72)
    K=9 -> MAE moyenne = 29.88 (BP: 12.64 | Chol: 47.12)
    K=10 -> MAE moyenne = 29.76 (BP: 12.79 | Chol: 46.74)
    K=11 -> MAE moyenne = 29.76 (BP: 12.90 | Chol: 46.61)

 RÉSULTATS FINAUX (moyenne sur les 3 tests)
K=3 -> MAE moyenne = 34.51
K=5 -> MAE moyenne = 32.56
K=7 -> MAE moyenne = 31.48
K=9 -> MAE moyenne = 30.86
K=10 -> MAE moyenne = 30.66
K=11 -> MAE moyenne = 30.31
 MEILLEUR K : K = 11  (MAE moyenne = 30.31)
NaN restants après imputation : 0

In [20]:
df['Cholesterol'].isnull().sum()

np.int64(0)

In [21]:
df['RestingBP'].isnull().sum()

np.int64(0)

In [22]:
df.to_csv("../data/processed/heart_clean.csv",index=False)